feature: create all components
tjolr/tdt4240_project pull request #25
Opened 2021-03-22 22:30 UTC by VidarMich

Several components are currently just dummies, but all should be usable.

These components are the ones necessary to develop the game.

2021-03-22 22:32 UTC, VidarMich commented
It seems that I've misunderstood rebasing. Will fix tomorrow.

2021-03-23 07:45 UTC, tjolr commented on core/src/com/mygdx/game/ecs/components/BotComponent.java
> +    //todo skal kanskje være tom
Enig at den kan nok være tom.

2021-03-23 07:45 UTC, tjolr commented on core/src/com/mygdx/game/ecs/components/CollisionComponent.java
> +    //todo skal kanskje være tom
Kan nok og være tom

2021-03-23 07:50 UTC, tjolr requested changes
Ser bra ut det her Vidar :-) 

Enig i kommentarene dine på botComponent og CollisionComponent at de kan være tomme enn så lenge. 

Slik det er nå har du 3 commits som egentlig er 1 commit. Gjerne resett disse comittene til en commit, og push opp til branch igjen :)

2021-03-23 09:16 UTC, VidarMich commented on core/src/com/mygdx/game/ecs/components/BotComponent.java
> +    //todo skal kanskje være tom
Tømte den nå

2021-03-23 09:16 UTC, VidarMich commented on core/src/com/mygdx/game/ecs/components/CollisionComponent.java
> +    //todo skal kanskje være tom
Denne er også tom nå

2021-03-23 09:16 UTC, VidarMich commented
Med hjelp fra Tjøl fikk jeg fikset en ny PR med kun én commit.

2021-03-23 09:32 UTC, tjolr approved these changes

2021-03-23 09:46 UTC, merged